### ISSUE TITLE
German language??

### ISSUE THREAD

**Issue by AlfaOmega33** [happyalu/Flite-TTS-Engine-for-Android#54]

**Comment by davidak** [comment]
@AlfaOmega33 so we have now german language support or why is it closed?

**Comment by AlfaOmega33** [comment]
1) sorry for the retard!

2) what I understood from, the new languages are managed from the community of translators and not from the developer same .. so makes no sense to create a issue here. If I'm wrong, I reopen the issue, of course

**Comment by alexander255** [comment]
@davidak: The official path for adding new languages is to first create/find a usable [festival](http://festvox.org/) voice, then follow the [flite voice conversion guide](http://festvox.org/flite/doc/flite_8.html#Converting-FestVox-Voices) to port these voices over to flite binaries.

*So what would that mean for having a German voice?*
Well the only German voice that appears to be publicly available is the [Austrian-German Leopold Voice](https://sourceforge.net/projects/at-festival/). Getting it to work on current festival is trivial (just remove the custom-shipped engine). However, porting it over to flite is another matter… Based on the flite documentation is looks like doing so requires an intricate knowledge of the used speech engine and quite a bit of trial and error.
As a matter of fact it may even be easier to port the festival engine to Android instead: Unlike porting a language to flite, porting festival to some other platform is a much simpler task because (a) anything that can run scheme, can run festival, and (b) both the relevant Android and festival APIs are at least somewhat documented and boil down to "synthesize this piece of text, please" (much easier to grasp problem space).

Feel like taking a stab at this? :grin:

@AlfaOmega33: Yes downloads are managed by CMU at http://festvox.org/flite/voices/cg/voxdata-v2.0.0/

**Comment by davidak** [comment]
Thanks for clarification!

I would like to have german TTS running locally on Android, but it's not that important that i would use my free time for that. Already have too much projects :D
