### ISSUE TITLE
error of flite.h

### ISSUE THREAD

**Issue by BhumikaeTech** [happyalu/Flite-TTS-Engine-for-Android#57]
hello,
In edu_cmu_cs_speech_tts_flite_service.cc file there is include<flite.h> header tag. Give me unresolved inclusion and also give me error at 'NULL' value. 

- I have attached Image here. Red line on 'NULL' value and also error in another files where flite.h is not found. See in left panel (project structure)

![screenshot from 2016-12-26 20 15 06](https://cloud.githubusercontent.com/assets/19589425/21483406/9090faf6-cba7-11e6-99ff-fc4103e49bc5.png)

- So, I can not generete .so file under libs folder

**Comment by alexander255** [comment]
I have never used Eclipse with this before, but the error you're seeing is not an *Android Flite TTS Engine* error, but an Eclipse configuration error. To fix to you'll have to:

  1. Run `./build.sh` at least once to download and build the Flite engine itself
  2. Configure Eclipse to search `<project dir>/flite/flite-2.0.0-release/include` when looking for C includes
  3. Either set up Eclipse to set the environment variable `FLITEDIR` to `<project dir>/flite/flite-2.0.0-release` when invoking `ant` OR tell Eclipse to run `./build.sh` instead of `ant`

None of the above has been tested, but it should help you look in the right places to fix these errors.

**Comment by happyalu** [comment]
Thanks, @alexander255 for the help. I'm closing this issue.
